idf_component_register(
    SRCS
        "app_main.c"
        "board_i2c.c"
        "ads1115.c"
        "analog_input.c"
        "digital_input.c"
        "lora_periodic_sender.c"
        "lora_receiver.c"
        "lora_uart.c"
        "modbus_slave.c"
        "relay_driver.c"
        "rv3028.c"
        "rs485_control.c"
        "web_config.c"
    INCLUDE_DIRS "."
    REQUIRES
        app_update
        driver
        esp_event
        esp_http_server
        esp_netif
        esp_wifi
        nvs_flash
)
